# Generated by Django 4.0.5 on 2022-06-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('title',)},
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('L', 'Low-priority'), ('I', 'Important'), ('N', 'Not important'), ('U', 'Urgent'), ('X', 'Xtra Important')], max_length=50),
        ),
    ]
