# Generated by Django 4.0.5 on 2022-06-04 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_comment_alter_task_title_issue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='comments',
        ),
    ]
