# Generated by Django 4.0.5 on 2022-06-06 08:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_rename_name_comment_user_remove_issue_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='submitted_by',
            field=models.ManyToManyField(default='', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='threat_level',
            field=models.CharField(choices=[('1', 'Minor'), ('2', 'Moderate'), ('3', 'Critical'), ('4', 'Dangerous')], max_length=50),
        ),
    ]
